{% set name = "h5pywrappers" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/h5pywrappers-{{ version }}.tar.gz
  sha256: e1552b9e3c15313ee28c7e6a8c82b641c3008dbfdcae236c3da1fd739cb0a3f5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - czekitout >=1.0.0
    - fancytypes >=1.0.0
    - h5py

test:
  imports:
    - h5pywrappers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/h5pywrappers/
  summary: Contains several functions used to facilitate loading data from and saving data to HDF5 files. These functions are wrappers that call functions from the library ``h5py``.
  dev_url: https://github.com/mrfitzpa/h5pywrappers
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mrfitzpa
