{% set name = "h5pywrappers" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/h5pywrappers-{{ version }}.tar.gz
  sha256: 9589bca918434b40bba32faa47c33f3c421d0a606feda3009212278d02c012f1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - czekitout >=1.0.0
    - fancytypes >=1.0.0
    - h5py

test:
  imports:
    - h5pywrappers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/h5pywrappers/
  summary: Contains several functions used to facilitate loading data from and saving data to HDF5 files. These functions are wrappers that call functions from the library ``h5py``.
  dev_url: https://github.com/mrfitzpa/h5pywrappers
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mrfitzpa
